name: CI

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.7-alpine
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: deploy lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: eu-north-1
      run: |
        apk add --no-cache musl-dev gcc
        pip install awscli aws-sam-cli pip==19.2.3
        sam build
        sam package --output-template-file packaged.yaml --s3-bucket menoinfo-scraper
        sam deploy --template-file packaged.yaml --stack-name lalala --capabilities CAPABILITY_IAM
